version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - "mazrean"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - "mazrean"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - "mazrean"
    labels:
      - "dependencies"
      - "github_actions"
