before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=1
      - >-
          {{- if eq .Os "darwin" }}
            {{- if eq .Arch "amd64"}}CC=zig c -target x86_64-macos-none -F{{ .Env.SDK_PATH }}/System/Library/Frameworks{{- end }}
            {{- if eq .Arch "arm64"}}CC=zig c -target aarch64-macos-none -F{{ .Env.SDK_PATH }}/System/Library/Frameworks{{- end }}
          {{- end }}
      - >-
          {{- if eq .Os "darwin" }}
            {{- if eq .Arch "amd64"}}CC=zig c++ -target x86_64-macos-none -F{{ .Env.SDK_PATH }}/System/Library/Frameworks{{- end }}
            {{- if eq .Arch "arm64"}}CC=zig c++ -target aarch64-macos-none -F{{ .Env.SDK_PATH }}/System/Library/Frameworks{{- end }}
          {{- end }}
      - >-
          {{- if eq .Os "linux" }}
            {{- if eq .Arch "amd64" }}CC=zig c -target x86_64-linux-musl{{- end }}
            {{- if eq .Arch "arm64"}}CC=zig c -target aarch64-linux-musl{{- end }}
          {{- end }}
      - >-
          {{- if eq .Os "linux" }}
            {{- if eq .Arch "amd64" }}CC=zig c++ -target x86_64-linux-musl{{- end }}
            {{- if eq .Arch "arm64"}}CC=zig c++ -target aarch64-linux-musl{{- end }}
          {{- end }}
      - >-
          {{- if eq .Os "windows" }}
            {{- if eq .Arch "amd64" }}CC=zig c -target x86_64-windows-gnu{{- end }}
            {{- if eq .Arch "arm64"}}CC=zig c -target aarch64-windows-gnu{{- end }}
          {{- end }}
      - >-
          {{- if eq .Os "windows" }}
            {{- if eq .Arch "amd64" }}CC=zig c++ -target x86_64-windows-gnu{{- end }}
            {{- if eq .Arch "arm64"}}CC=zig c++ -target aarch64-windows-gnu{{- end }}
          {{- end }}
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
      - -X main.version={{.Version}}
      - -X main.revision={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
    main: ./

archives:
  - format: binary
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
release:
  extra_files:
    - name_template: LICENSE
      glob: LICENSE
    - name_template: README.md
      glob: README.md
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
