before:
  hooks:
    - go mod download
builds:
  - id: linux
    env:
      - CGO_ENABLED=1
      - >-
          {{- if eq .Os "linux" }}
            {{- if eq .Arch "amd64" }}CC=zig cc -target x86_64-linux-musl{{- end }}
            {{- if eq .Arch "arm64"}}CC=zig cc -target aarch64-linux-musl{{- end }}
          {{- end }}
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
      - -X main.version={{.Version}}
      - -X main.revision={{.ShortCommit}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./
  - id: windows
    env:
      - CGO_ENABLED=1
      - >-
          {{- if eq .Os "windows" }}
            {{- if eq .Arch "amd64" }}CC=zig cc -target x86_64-windows-gnu{{- end }}
            {{- if eq .Arch "arm64"}}CC=zig cc -target aarch64-windows-gnu{{- end }}
          {{- end }}
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
      - -X main.version={{.Version}}
      - -X main.revision={{.ShortCommit}}
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    main: ./
  - id: darwin
    env:
      - CGO_ENABLED=1
      - >-
          {{- if eq .Os "darwin" }}
            {{- if eq .Arch "amd64"}}CC=zig cc -target x86_64-macos-none --sysroot "{{ .Env.SDK_ROOT }}" -I/usr/include -F{{ .Env.SDK_ROOT }}/System/Library/Frameworks -L/usr/lib{{- end }}
            {{- if eq .Arch "arm64"}}CC=zig cc -target aarch64-macos-none --sysroot "{{ .Env.SDK_ROOT }}" -I/usr/include -F{{ .Env.SDK_ROOT }}/System/Library/Frameworks -L/usr/lib{{- end }}
          {{- end }}
    flags:
      - -trimpath
      - -buildmode=pie
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
      - -X main.version={{.Version}}
      - -X main.revision={{.ShortCommit}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./

archives:
  - format: binary
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
release:
  extra_files:
    - name_template: LICENSE
      glob: LICENSE
    - name_template: README.md
      glob: README.md
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
