// Code generated by odjson. DO NOT EDIT.
//
// Source: odjson -type Request,Response

package protocol

import (
	"bytes"
	"encoding/json/jsontext"
	"github.com/mazrean/odjson/odjsonrt"
)

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Request) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"ID\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.ID))
	dst = append(dst, ",\"Command\":\""...)
	dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.Command), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, "\""...)
	if v.ActionID != "" {
		dst = append(dst, ",\"ActionID\":\""...)
		dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.ActionID), m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, "\""...)
	}
	if v.OutputID != "" {
		dst = append(dst, ",\"OutputID\":\""...)
		dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.OutputID), m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, "\""...)
	}
	if v.BodySize != 0 {
		dst = append(dst, ",\"BodySize\":"...)
		dst = odjsonrt.AppendInt(dst, int64(v.BodySize))
	}
	dst[start] = '{'
	dst = append(dst, "}"...)
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Request) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Request")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 'I':
				if len(rest) >= 4 && string(rest[:4]) == "\"ID\"" {
					idx, p = 0, p+4
				}
			case 'C':
				if len(rest) >= 9 && string(rest[:9]) == "\"Command\"" {
					idx, p = 1, p+9
				}
			case 'A':
				if len(rest) >= 10 && string(rest[:10]) == "\"ActionID\"" {
					idx, p = 2, p+10
				}
			case 'O':
				if len(rest) >= 10 && string(rest[:10]) == "\"OutputID\"" {
					idx, p = 3, p+10
				}
			case 'B':
				if len(rest) >= 10 && string(rest[:10]) == "\"BodySize\"" {
					idx, p = 4, p+10
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "ID":
				idx = 0
			case "Command":
				idx = 1
			case "ActionID":
				idx = 2
			case "OutputID":
				idx = 3
			case "BodySize":
				idx = 4
			}
		}
		switch idx {
		case 0:
			if np1, ok2 := odjsonrt.ParseNull(data, p); ok2 {
				p = np1
			} else {
				if x3, np4, ok5 := odjsonrt.ParseDecimal(data, p); ok5 {
					v.ID = int64(x3)
					p = np4
				} else {
					var x6 int64
					x6, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.ID = x6
				}
			}
		case 1:
			if np7, ok8 := odjsonrt.ParseNull(data, p); ok8 {
				p = np7
			} else {
				var x9 string
				x9, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Command = Cmd(x9)
			}
		case 2:
			if np10, ok11 := odjsonrt.ParseNull(data, p); ok11 {
				p = np10
			} else {
				var x12 string
				x12, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.ActionID = x12
			}
		case 3:
			if np13, ok14 := odjsonrt.ParseNull(data, p); ok14 {
				p = np13
			} else {
				var x15 string
				x15, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.OutputID = x15
			}
		case 4:
			if np16, ok17 := odjsonrt.ParseNull(data, p); ok17 {
				p = np16
			} else {
				if x18, np19, ok20 := odjsonrt.ParseDecimal(data, p); ok20 {
					v.BodySize = int64(x18)
					p = np19
				} else {
					var x21 int64
					x21, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.BodySize = x21
				}
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if uint(p) >= uint(len(data)) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Request) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Request{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Request")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	for {
		var key []byte
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 'I':
				if len(rest) >= 4 && string(rest[:4]) == "\"ID\"" {
					idx, p = 0, p+4
				}
			case 'C':
				if len(rest) >= 9 && string(rest[:9]) == "\"Command\"" {
					idx, p = 1, p+9
				}
			case 'A':
				if len(rest) >= 10 && string(rest[:10]) == "\"ActionID\"" {
					idx, p = 2, p+10
				}
			case 'O':
				if len(rest) >= 10 && string(rest[:10]) == "\"OutputID\"" {
					idx, p = 3, p+10
				}
			case 'B':
				if len(rest) >= 10 && string(rest[:10]) == "\"BodySize\"" {
					idx, p = 4, p+10
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "ID":
				idx = 0
			case "Command":
				idx = 1
			case "ActionID":
				idx = 2
			case "OutputID":
				idx = 3
			case "BodySize":
				idx = 4
			}
		}
		switch idx {
		case 0:
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np22, ok23 := odjsonrt.ParseNull(data, p); ok23 {
				p = np22
				v.ID = 0
			} else {
				if x24, np25, ok26 := odjsonrt.ParseDecimal(data, p); ok26 {
					v.ID = int64(x24)
					p = np25
				} else {
					var x27 int64
					x27, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.ID = x27
				}
			}
		case 1:
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np28, ok29 := odjsonrt.ParseNull(data, p); ok29 {
				p = np28
				v.Command = ""
			} else {
				var x30 string
				x30, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.Command = Cmd(x30)
			}
		case 2:
			if strict && seen[0]&(1<<2) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 2
			if np31, ok32 := odjsonrt.ParseNull(data, p); ok32 {
				p = np31
				v.ActionID = ""
			} else {
				var x33 string
				x33, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.ActionID = x33
			}
		case 3:
			if strict && seen[0]&(1<<3) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 3
			if np34, ok35 := odjsonrt.ParseNull(data, p); ok35 {
				p = np34
				v.OutputID = ""
			} else {
				var x36 string
				x36, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.OutputID = x36
			}
		case 4:
			if strict && seen[0]&(1<<4) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 4
			if np37, ok38 := odjsonrt.ParseNull(data, p); ok38 {
				p = np37
				v.BodySize = 0
			} else {
				if x39, np40, ok41 := odjsonrt.ParseDecimal(data, p); ok41 {
					v.BodySize = int64(x39)
					p = np40
				} else {
					var x42 int64
					x42, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.BodySize = x42
				}
			}
		default:
			if strict {
				for _, u := range unknown[umark:] {
					if string(u) == string(key) {
						return kp, odjsonrt.ErrDuplicateName(data, kp, key)
					}
				}
				unknown = odjsonrt.AddUnknownName(sc, unknown, key)
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if uint(p) >= uint(len(data)) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			odjsonrt.EndUnknownNames(sc, unknown, umark)
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Request) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Request{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Request")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"ID\"":
			idx = 0
		case "\"Command\"":
			idx = 1
		case "\"ActionID\"":
			idx = 2
		case "\"OutputID\"":
			idx = 3
		case "\"BodySize\"":
			idx = 4
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "ID":
					idx = 0
				case "Command":
					idx = 1
				case "ActionID":
					idx = 2
				case "OutputID":
					idx = 3
				case "BodySize":
					idx = 4
				}
			}
		}
		switch idx {
		case 0:
			var val43 jsontext.Value
			val43, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val43[0] == 'n' {
				v.ID = 0
			} else {
				var x44 int64
				x44, _, err = odjsonrt.ParseInt(val43, 0, 64)
				if err != nil {
					return err
				}
				v.ID = x44
			}
		case 1:
			var val45 jsontext.Value
			val45, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val45[0] == 'n' {
				v.Command = ""
			} else {
				var x46 string
				x46, err = odjsonrt.ParseStringValue(val45, sc)
				if err != nil {
					return err
				}
				v.Command = Cmd(x46)
			}
		case 2:
			var val47 jsontext.Value
			val47, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val47[0] == 'n' {
				v.ActionID = ""
			} else {
				var x48 string
				x48, err = odjsonrt.ParseStringValue(val47, sc)
				if err != nil {
					return err
				}
				v.ActionID = x48
			}
		case 3:
			var val49 jsontext.Value
			val49, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val49[0] == 'n' {
				v.OutputID = ""
			} else {
				var x50 string
				x50, err = odjsonrt.ParseStringValue(val49, sc)
				if err != nil {
					return err
				}
				v.OutputID = x50
			}
		case 4:
			var val51 jsontext.Value
			val51, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val51[0] == 'n' {
				v.BodySize = 0
			} else {
				var x52 int64
				x52, _, err = odjsonrt.ParseInt(val51, 0, 64)
				if err != nil {
					return err
				}
				v.BodySize = x52
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizeRequest sizes the buffer the encoders allocate.
var odjsonSizeRequest odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Request) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeRequest.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeRequest.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Request) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Request) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizeRequest.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizeRequest.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Request) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Response) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"ID\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.ID))
	if v.Err != "" {
		dst = append(dst, ",\"Err\":\""...)
		dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.Err), m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, "\""...)
	}
	if v.KnownCommands != nil {
		if v.KnownCommands == nil {
			if m.V2() {
				dst = append(dst, ",\"KnownCommands\""...)
				dst = append(dst, ":[]"...)
			} else {
				dst = append(dst, ",\"KnownCommands\""...)
				dst = append(dst, ":null"...)
			}
		} else {
			dst = append(dst, ",\"KnownCommands\""...)
			dst = append(dst, ":["...)
			for i53 := range v.KnownCommands {
				if i53 > 0 {
					dst = append(dst, ',')
				}
				dst = append(dst, "\""...)
				dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.KnownCommands[i53]), m)
				if err != nil {
					return nil, err
				}
				dst = append(dst, "\""...)
			}
			dst = append(dst, "]"...)
		}
	}
	if v.Miss != false {
		if bool(v.Miss) {
			dst = append(dst, ",\"Miss\":true"...)
		} else {
			dst = append(dst, ",\"Miss\":false"...)
		}
	}
	if v.OutputID != "" {
		dst = append(dst, ",\"OutputID\":\""...)
		dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.OutputID), m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, "\""...)
	}
	if v.Size != 0 {
		dst = append(dst, ",\"Size\":"...)
		dst = odjsonrt.AppendInt(dst, int64(v.Size))
	}
	if v.TimeNanos != 0 {
		dst = append(dst, ",\"TimeNanos\":"...)
		dst = odjsonrt.AppendInt(dst, int64(v.TimeNanos))
	}
	if v.DiskPath != "" {
		dst = append(dst, ",\"DiskPath\":\""...)
		dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.DiskPath), m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, "\""...)
	}
	dst[start] = '{'
	dst = append(dst, "}"...)
	return dst, nil
}

// odjsonCapResponseKnownCommands remembers how long v.KnownCommands has been, to allocate it once.
var odjsonCapResponseKnownCommands odjsonrt.CapHint

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Response) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Response")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 'I':
				if len(rest) >= 4 && string(rest[:4]) == "\"ID\"" {
					idx, p = 0, p+4
				}
			case 'E':
				if len(rest) >= 5 && string(rest[:5]) == "\"Err\"" {
					idx, p = 1, p+5
				}
			case 'K':
				if len(rest) >= 15 && string(rest[:15]) == "\"KnownCommands\"" {
					idx, p = 2, p+15
				}
			case 'M':
				if len(rest) >= 6 && string(rest[:6]) == "\"Miss\"" {
					idx, p = 3, p+6
				}
			case 'O':
				if len(rest) >= 10 && string(rest[:10]) == "\"OutputID\"" {
					idx, p = 4, p+10
				}
			case 'S':
				if len(rest) >= 6 && string(rest[:6]) == "\"Size\"" {
					idx, p = 5, p+6
				}
			case 'T':
				if len(rest) >= 11 && string(rest[:11]) == "\"TimeNanos\"" {
					idx, p = 6, p+11
				}
			case 'D':
				if len(rest) >= 10 && string(rest[:10]) == "\"DiskPath\"" {
					idx, p = 7, p+10
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "ID":
				idx = 0
			case "Err":
				idx = 1
			case "KnownCommands":
				idx = 2
			case "Miss":
				idx = 3
			case "OutputID":
				idx = 4
			case "Size":
				idx = 5
			case "TimeNanos":
				idx = 6
			case "DiskPath":
				idx = 7
			}
		}
		switch idx {
		case 0:
			if np54, ok55 := odjsonrt.ParseNull(data, p); ok55 {
				p = np54
			} else {
				if x56, np57, ok58 := odjsonrt.ParseDecimal(data, p); ok58 {
					v.ID = int64(x56)
					p = np57
				} else {
					var x59 int64
					x59, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.ID = x59
				}
			}
		case 1:
			if np60, ok61 := odjsonrt.ParseNull(data, p); ok61 {
				p = np60
			} else {
				var x62 string
				x62, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Err = x62
			}
		case 2:
			if np63, ok64 := odjsonrt.ParseNull(data, p); ok64 {
				p = np63
				v.KnownCommands = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]Cmd")
				}
				p++
				s65 := v.KnownCommands[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s65) == 0 {
						s65 = make([]Cmd, 0, odjsonrt.CapFor[Cmd](&odjsonCapResponseKnownCommands))
					}
					for {
						var e66 Cmd
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						if np67, ok68 := odjsonrt.ParseNull(data, p); ok68 {
							p = np67
						} else {
							var x69 string
							x69, p, err = odjsonrt.ParseStringCached(data, p, sc)
							if err != nil {
								return p, err
							}
							e66 = Cmd(x69)
						}
						s65 = append(s65, e66)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapResponseKnownCommands.Record(len(s65))
				}
				if s65 == nil {
					s65 = []Cmd{}
				}
				v.KnownCommands = s65
			}
		case 3:
			if np70, ok71 := odjsonrt.ParseNull(data, p); ok71 {
				p = np70
			} else {
				if uint(p+4) <= uint(len(data)) && string(data[p:p+4]) == "true" {
					v.Miss = true
					p += 4
				} else if uint(p+5) <= uint(len(data)) && string(data[p:p+5]) == "false" {
					v.Miss = false
					p += 5
				} else {
					var x72 bool
					x72, p, err = odjsonrt.ParseBool(data, p)
					if err != nil {
						return p, err
					}
					v.Miss = x72
				}
			}
		case 4:
			if np73, ok74 := odjsonrt.ParseNull(data, p); ok74 {
				p = np73
			} else {
				var x75 string
				x75, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.OutputID = x75
			}
		case 5:
			if np76, ok77 := odjsonrt.ParseNull(data, p); ok77 {
				p = np76
			} else {
				if x78, np79, ok80 := odjsonrt.ParseDecimal(data, p); ok80 {
					v.Size = int64(x78)
					p = np79
				} else {
					var x81 int64
					x81, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.Size = x81
				}
			}
		case 6:
			if np82, ok83 := odjsonrt.ParseNull(data, p); ok83 {
				p = np82
			} else {
				if x84, np85, ok86 := odjsonrt.ParseDecimal(data, p); ok86 {
					v.TimeNanos = int64(x84)
					p = np85
				} else {
					var x87 int64
					x87, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.TimeNanos = x87
				}
			}
		case 7:
			if np88, ok89 := odjsonrt.ParseNull(data, p); ok89 {
				p = np88
			} else {
				var x90 string
				x90, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.DiskPath = x90
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if uint(p) >= uint(len(data)) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Response) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Response{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Response")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	for {
		var key []byte
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 'I':
				if len(rest) >= 4 && string(rest[:4]) == "\"ID\"" {
					idx, p = 0, p+4
				}
			case 'E':
				if len(rest) >= 5 && string(rest[:5]) == "\"Err\"" {
					idx, p = 1, p+5
				}
			case 'K':
				if len(rest) >= 15 && string(rest[:15]) == "\"KnownCommands\"" {
					idx, p = 2, p+15
				}
			case 'M':
				if len(rest) >= 6 && string(rest[:6]) == "\"Miss\"" {
					idx, p = 3, p+6
				}
			case 'O':
				if len(rest) >= 10 && string(rest[:10]) == "\"OutputID\"" {
					idx, p = 4, p+10
				}
			case 'S':
				if len(rest) >= 6 && string(rest[:6]) == "\"Size\"" {
					idx, p = 5, p+6
				}
			case 'T':
				if len(rest) >= 11 && string(rest[:11]) == "\"TimeNanos\"" {
					idx, p = 6, p+11
				}
			case 'D':
				if len(rest) >= 10 && string(rest[:10]) == "\"DiskPath\"" {
					idx, p = 7, p+10
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "ID":
				idx = 0
			case "Err":
				idx = 1
			case "KnownCommands":
				idx = 2
			case "Miss":
				idx = 3
			case "OutputID":
				idx = 4
			case "Size":
				idx = 5
			case "TimeNanos":
				idx = 6
			case "DiskPath":
				idx = 7
			}
		}
		switch idx {
		case 0:
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np91, ok92 := odjsonrt.ParseNull(data, p); ok92 {
				p = np91
				v.ID = 0
			} else {
				if x93, np94, ok95 := odjsonrt.ParseDecimal(data, p); ok95 {
					v.ID = int64(x93)
					p = np94
				} else {
					var x96 int64
					x96, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.ID = x96
				}
			}
		case 1:
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np97, ok98 := odjsonrt.ParseNull(data, p); ok98 {
				p = np97
				v.Err = ""
			} else {
				var x99 string
				x99, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.Err = x99
			}
		case 2:
			if strict && seen[0]&(1<<2) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 2
			if np100, ok101 := odjsonrt.ParseNull(data, p); ok101 {
				p = np100
				v.KnownCommands = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]Cmd")
				}
				p++
				s102 := v.KnownCommands[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s102) == 0 {
						s102 = make([]Cmd, 0, odjsonrt.CapFor[Cmd](&odjsonCapResponseKnownCommands))
					}
					for {
						var e103 Cmd
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						if np104, ok105 := odjsonrt.ParseNull(data, p); ok105 {
							p = np104
							e103 = ""
						} else {
							var x106 string
							x106, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
							if err != nil {
								return p, err
							}
							e103 = Cmd(x106)
						}
						s102 = append(s102, e103)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapResponseKnownCommands.Record(len(s102))
				}
				if s102 == nil {
					s102 = []Cmd{}
				}
				v.KnownCommands = s102
			}
		case 3:
			if strict && seen[0]&(1<<3) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 3
			if np107, ok108 := odjsonrt.ParseNull(data, p); ok108 {
				p = np107
				v.Miss = false
			} else {
				if uint(p+4) <= uint(len(data)) && string(data[p:p+4]) == "true" {
					v.Miss = true
					p += 4
				} else if uint(p+5) <= uint(len(data)) && string(data[p:p+5]) == "false" {
					v.Miss = false
					p += 5
				} else {
					var x109 bool
					x109, p, err = odjsonrt.ParseBool(data, p)
					if err != nil {
						return p, err
					}
					v.Miss = x109
				}
			}
		case 4:
			if strict && seen[0]&(1<<4) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 4
			if np110, ok111 := odjsonrt.ParseNull(data, p); ok111 {
				p = np110
				v.OutputID = ""
			} else {
				var x112 string
				x112, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.OutputID = x112
			}
		case 5:
			if strict && seen[0]&(1<<5) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 5
			if np113, ok114 := odjsonrt.ParseNull(data, p); ok114 {
				p = np113
				v.Size = 0
			} else {
				if x115, np116, ok117 := odjsonrt.ParseDecimal(data, p); ok117 {
					v.Size = int64(x115)
					p = np116
				} else {
					var x118 int64
					x118, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.Size = x118
				}
			}
		case 6:
			if strict && seen[0]&(1<<6) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 6
			if np119, ok120 := odjsonrt.ParseNull(data, p); ok120 {
				p = np119
				v.TimeNanos = 0
			} else {
				if x121, np122, ok123 := odjsonrt.ParseDecimal(data, p); ok123 {
					v.TimeNanos = int64(x121)
					p = np122
				} else {
					var x124 int64
					x124, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.TimeNanos = x124
				}
			}
		case 7:
			if strict && seen[0]&(1<<7) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 7
			if np125, ok126 := odjsonrt.ParseNull(data, p); ok126 {
				p = np125
				v.DiskPath = ""
			} else {
				var x127 string
				x127, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.DiskPath = x127
			}
		default:
			if strict {
				for _, u := range unknown[umark:] {
					if string(u) == string(key) {
						return kp, odjsonrt.ErrDuplicateName(data, kp, key)
					}
				}
				unknown = odjsonrt.AddUnknownName(sc, unknown, key)
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if uint(p) >= uint(len(data)) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			odjsonrt.EndUnknownNames(sc, unknown, umark)
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Response) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Response{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Response")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"ID\"":
			idx = 0
		case "\"Err\"":
			idx = 1
		case "\"KnownCommands\"":
			idx = 2
		case "\"Miss\"":
			idx = 3
		case "\"OutputID\"":
			idx = 4
		case "\"Size\"":
			idx = 5
		case "\"TimeNanos\"":
			idx = 6
		case "\"DiskPath\"":
			idx = 7
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "ID":
					idx = 0
				case "Err":
					idx = 1
				case "KnownCommands":
					idx = 2
				case "Miss":
					idx = 3
				case "OutputID":
					idx = 4
				case "Size":
					idx = 5
				case "TimeNanos":
					idx = 6
				case "DiskPath":
					idx = 7
				}
			}
		}
		switch idx {
		case 0:
			var val128 jsontext.Value
			val128, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val128[0] == 'n' {
				v.ID = 0
			} else {
				var x129 int64
				x129, _, err = odjsonrt.ParseInt(val128, 0, 64)
				if err != nil {
					return err
				}
				v.ID = x129
			}
		case 1:
			var val130 jsontext.Value
			val130, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val130[0] == 'n' {
				v.Err = ""
			} else {
				var x131 string
				x131, err = odjsonrt.ParseStringValue(val130, sc)
				if err != nil {
					return err
				}
				v.Err = x131
			}
		case 2:
			var val132 jsontext.Value
			val132, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp133 := 0
			if np134, ok135 := odjsonrt.ParseNull(val132, vp133); ok135 {
				vp133 = np134
				v.KnownCommands = nil
			} else {
				if uint(vp133) >= uint(len(val132)) || val132[vp133] != '[' {
					return odjsonrt.ErrType(val132, vp133, "[]Cmd")
				}
				vp133++
				s136 := v.KnownCommands[:0]
				vp133 = odjsonrt.SkipSpace(val132, vp133)
				if uint(vp133) < uint(len(val132)) && val132[vp133] == ']' {
					vp133++
				} else {
					if cap(s136) == 0 {
						s136 = make([]Cmd, 0, odjsonrt.CapFor[Cmd](&odjsonCapResponseKnownCommands))
					}
					for {
						var e137 Cmd
						if uint(vp133) >= uint(len(val132)) || val132[vp133] <= ' ' {
							vp133 = odjsonrt.SkipSpace(val132, odjsonrt.SkipIndent(val132, vp133))
						}
						if np138, ok139 := odjsonrt.ParseNull(val132, vp133); ok139 {
							vp133 = np138
							e137 = ""
						} else {
							var x140 string
							x140, vp133, err = odjsonrt.ParseStringWith(val132, vp133, sc)
							if err != nil {
								return err
							}
							e137 = Cmd(x140)
						}
						s136 = append(s136, e137)
						vp133 = odjsonrt.SkipSpace(val132, vp133)
						if uint(vp133) >= uint(len(val132)) {
							return odjsonrt.ErrSyntax(val132, vp133, "unexpected end of JSON input")
						}
						if val132[vp133] == ',' {
							vp133++
							continue
						}
						if val132[vp133] == ']' {
							vp133++
							break
						}
						return odjsonrt.ErrSyntax(val132, vp133, "after array element")
					}
					odjsonCapResponseKnownCommands.Record(len(s136))
				}
				if s136 == nil {
					s136 = []Cmd{}
				}
				v.KnownCommands = s136
			}
			_ = vp133
		case 3:
			var val141 jsontext.Value
			val141, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val141[0] == 'n' {
				v.Miss = false
			} else {
				var x142 bool
				x142, _, err = odjsonrt.ParseBool(val141, 0)
				if err != nil {
					return err
				}
				v.Miss = x142
			}
		case 4:
			var val143 jsontext.Value
			val143, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val143[0] == 'n' {
				v.OutputID = ""
			} else {
				var x144 string
				x144, err = odjsonrt.ParseStringValue(val143, sc)
				if err != nil {
					return err
				}
				v.OutputID = x144
			}
		case 5:
			var val145 jsontext.Value
			val145, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val145[0] == 'n' {
				v.Size = 0
			} else {
				var x146 int64
				x146, _, err = odjsonrt.ParseInt(val145, 0, 64)
				if err != nil {
					return err
				}
				v.Size = x146
			}
		case 6:
			var val147 jsontext.Value
			val147, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val147[0] == 'n' {
				v.TimeNanos = 0
			} else {
				var x148 int64
				x148, _, err = odjsonrt.ParseInt(val147, 0, 64)
				if err != nil {
					return err
				}
				v.TimeNanos = x148
			}
		case 7:
			var val149 jsontext.Value
			val149, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val149[0] == 'n' {
				v.DiskPath = ""
			} else {
				var x150 string
				x150, err = odjsonrt.ParseStringValue(val149, sc)
				if err != nil {
					return err
				}
				v.DiskPath = x150
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizeResponse sizes the buffer the encoders allocate.
var odjsonSizeResponse odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Response) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeResponse.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeResponse.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Response) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Response) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizeResponse.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizeResponse.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Response) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}
