// Code generated by MockGen. DO NOT EDIT.
// Source: download.go
//
// Generated by this command:
//
//	mockgen -source=download.go -destination=mock/download.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDownloadClient is a mock of DownloadClient interface.
type MockDownloadClient struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadClientMockRecorder
	isgomock struct{}
}

// MockDownloadClientMockRecorder is the mock recorder for MockDownloadClient.
type MockDownloadClientMockRecorder struct {
	mock *MockDownloadClient
}

// NewMockDownloadClient creates a new mock instance.
func NewMockDownloadClient(ctrl *gomock.Controller) *MockDownloadClient {
	mock := &MockDownloadClient{ctrl: ctrl}
	mock.recorder = &MockDownloadClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadClient) EXPECT() *MockDownloadClientMockRecorder {
	return m.recorder
}

// DownloadBlock mocks base method.
func (m *MockDownloadClient) DownloadBlock(ctx context.Context, offset, size int64, w io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadBlock", ctx, offset, size, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadBlock indicates an expected call of DownloadBlock.
func (mr *MockDownloadClientMockRecorder) DownloadBlock(ctx, offset, size, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadBlock", reflect.TypeOf((*MockDownloadClient)(nil).DownloadBlock), ctx, offset, size, w)
}

// DownloadBlockBuffer mocks base method.
func (m *MockDownloadClient) DownloadBlockBuffer(ctx context.Context, offset, size int64, buf []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadBlockBuffer", ctx, offset, size, buf)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadBlockBuffer indicates an expected call of DownloadBlockBuffer.
func (mr *MockDownloadClientMockRecorder) DownloadBlockBuffer(ctx, offset, size, buf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadBlockBuffer", reflect.TypeOf((*MockDownloadClient)(nil).DownloadBlockBuffer), ctx, offset, size, buf)
}

// GetURL mocks base method.
func (m *MockDownloadClient) GetURL(ctx context.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetURL indicates an expected call of GetURL.
func (mr *MockDownloadClientMockRecorder) GetURL(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockDownloadClient)(nil).GetURL), ctx)
}
