// Code generated by kessoku. DO NOT EDIT.

package kessoku

import (
	"context"
	"github.com/mazrean/gocica/internal/cacheprog"
	"github.com/mazrean/gocica/internal/local"
	"github.com/mazrean/gocica/internal/remote"
	"github.com/mazrean/gocica/internal/remote/provider"
	"github.com/mazrean/gocica/log"
	"github.com/mazrean/gocica/protocol"
	"github.com/mazrean/kessoku"
)

func InitializeProcess(ctx context.Context, logger log.Logger, diskDir local.DiskDir, ghacacheConfig *provider.GHACacheConfig) (*protocol.Process, error) {
	var err error
	disk, err := kessoku.Async(kessoku.Bind[local.Backend](kessoku.Provide(local.NewDisk))).Fn()(logger, diskDir)
	if err != nil {
		var zero *protocol.Process
		return zero, err
	}
	var err0 error
	gitHubActionsCache, err0 := kessoku.Async(kessoku.Bind[remote.Backend](kessoku.Provide(provider.NewGitHubActionsCache))).Fn()(ctx, logger, ghacacheConfig, disk)
	if err0 != nil {
		var zero *protocol.Process
		return zero, err0
	}
	var err1 error
	conbinedBackend, err1 := kessoku.Async(kessoku.Bind[cacheprog.Backend](kessoku.Provide(cacheprog.NewConbinedBackend))).Fn()(logger, disk, gitHubActionsCache)
	if err1 != nil {
		var zero *protocol.Process
		return zero, err1
	}
	cacheProg := kessoku.Provide(cacheprog.NewCacheProg).Fn()(logger, conbinedBackend)
	process := kessoku.Provide(NewProcessWithOptions).Fn()(logger, cacheProg)
	return process, nil
}
