// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gocica/v1/actions_cache.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Compression int32

const (
	Compression_COMPRESSION_UNSPECIFIED Compression = 0
	Compression_COMPRESSION_ZSTD        Compression = 1
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "COMPRESSION_UNSPECIFIED",
		1: "COMPRESSION_ZSTD",
	}
	Compression_value = map[string]int32{
		"COMPRESSION_UNSPECIFIED": 0,
		"COMPRESSION_ZSTD":        1,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_gocica_v1_actions_cache_proto_enumTypes[0].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_gocica_v1_actions_cache_proto_enumTypes[0]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_gocica_v1_actions_cache_proto_rawDescGZIP(), []int{0}
}

type ActionsOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Compression   Compression            `protobuf:"varint,3,opt,name=compression,proto3,enum=gocica.v1.Compression" json:"compression,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionsOutput) Reset() {
	*x = ActionsOutput{}
	mi := &file_gocica_v1_actions_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionsOutput) ProtoMessage() {}

func (x *ActionsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_gocica_v1_actions_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionsOutput.ProtoReflect.Descriptor instead.
func (*ActionsOutput) Descriptor() ([]byte, []int) {
	return file_gocica_v1_actions_cache_proto_rawDescGZIP(), []int{0}
}

func (x *ActionsOutput) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ActionsOutput) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ActionsOutput) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_COMPRESSION_UNSPECIFIED
}

func (x *ActionsOutput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ActionsCache struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Entries         map[string]*IndexEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Outputs         []*ActionsOutput       `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	OutputTotalSize int64                  `protobuf:"varint,3,opt,name=output_total_size,json=outputTotalSize,proto3" json:"output_total_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActionsCache) Reset() {
	*x = ActionsCache{}
	mi := &file_gocica_v1_actions_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionsCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionsCache) ProtoMessage() {}

func (x *ActionsCache) ProtoReflect() protoreflect.Message {
	mi := &file_gocica_v1_actions_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionsCache.ProtoReflect.Descriptor instead.
func (*ActionsCache) Descriptor() ([]byte, []int) {
	return file_gocica_v1_actions_cache_proto_rawDescGZIP(), []int{1}
}

func (x *ActionsCache) GetEntries() map[string]*IndexEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ActionsCache) GetOutputs() []*ActionsOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ActionsCache) GetOutputTotalSize() int64 {
	if x != nil {
		return x.OutputTotalSize
	}
	return 0
}

var File_gocica_v1_actions_cache_proto protoreflect.FileDescriptor

const file_gocica_v1_actions_cache_proto_rawDesc = "" +
	"\n" +
	"\x1dgocica/v1/actions_cache.proto\x12\tgocica.v1\x1a\x1bgocica/v1/index_entry.proto\"\x85\x01\n" +
	"\rActionsOutput\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x128\n" +
	"\vcompression\x18\x03 \x01(\x0e2\x16.gocica.v1.CompressionR\vcompression\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"\x81\x02\n" +
	"\fActionsCache\x12>\n" +
	"\aentries\x18\x01 \x03(\v2$.gocica.v1.ActionsCache.EntriesEntryR\aentries\x122\n" +
	"\aoutputs\x18\x02 \x03(\v2\x18.gocica.v1.ActionsOutputR\aoutputs\x12*\n" +
	"\x11output_total_size\x18\x03 \x01(\x03R\x0foutputTotalSize\x1aQ\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.gocica.v1.IndexEntryR\x05value:\x028\x01*@\n" +
	"\vCompression\x12\x1b\n" +
	"\x17COMPRESSION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COMPRESSION_ZSTD\x10\x01B+Z)github.com/mazrean/gocica/proto/gocica/v1b\x06proto3"

var (
	file_gocica_v1_actions_cache_proto_rawDescOnce sync.Once
	file_gocica_v1_actions_cache_proto_rawDescData []byte
)

func file_gocica_v1_actions_cache_proto_rawDescGZIP() []byte {
	file_gocica_v1_actions_cache_proto_rawDescOnce.Do(func() {
		file_gocica_v1_actions_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gocica_v1_actions_cache_proto_rawDesc), len(file_gocica_v1_actions_cache_proto_rawDesc)))
	})
	return file_gocica_v1_actions_cache_proto_rawDescData
}

var file_gocica_v1_actions_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gocica_v1_actions_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gocica_v1_actions_cache_proto_goTypes = []any{
	(Compression)(0),      // 0: gocica.v1.Compression
	(*ActionsOutput)(nil), // 1: gocica.v1.ActionsOutput
	(*ActionsCache)(nil),  // 2: gocica.v1.ActionsCache
	nil,                   // 3: gocica.v1.ActionsCache.EntriesEntry
	(*IndexEntry)(nil),    // 4: gocica.v1.IndexEntry
}
var file_gocica_v1_actions_cache_proto_depIdxs = []int32{
	0, // 0: gocica.v1.ActionsOutput.compression:type_name -> gocica.v1.Compression
	3, // 1: gocica.v1.ActionsCache.entries:type_name -> gocica.v1.ActionsCache.EntriesEntry
	1, // 2: gocica.v1.ActionsCache.outputs:type_name -> gocica.v1.ActionsOutput
	4, // 3: gocica.v1.ActionsCache.EntriesEntry.value:type_name -> gocica.v1.IndexEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gocica_v1_actions_cache_proto_init() }
func file_gocica_v1_actions_cache_proto_init() {
	if File_gocica_v1_actions_cache_proto != nil {
		return
	}
	file_gocica_v1_index_entry_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gocica_v1_actions_cache_proto_rawDesc), len(file_gocica_v1_actions_cache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gocica_v1_actions_cache_proto_goTypes,
		DependencyIndexes: file_gocica_v1_actions_cache_proto_depIdxs,
		EnumInfos:         file_gocica_v1_actions_cache_proto_enumTypes,
		MessageInfos:      file_gocica_v1_actions_cache_proto_msgTypes,
	}.Build()
	File_gocica_v1_actions_cache_proto = out.File
	file_gocica_v1_actions_cache_proto_goTypes = nil
	file_gocica_v1_actions_cache_proto_depIdxs = nil
}
