// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: gocica/v1/index-entry.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexEntry is a single entry in the index.
type IndexEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiskPath string `protobuf:"bytes,1,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	OutputId string `protobuf:"bytes,2,opt,name=output_id,json=outputId,proto3" json:"output_id,omitempty"`
	Size     int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Timenano int64  `protobuf:"varint,4,opt,name=timenano,proto3" json:"timenano,omitempty"`
}

func (x *IndexEntry) Reset() {
	*x = IndexEntry{}
	mi := &file_gocica_v1_index_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexEntry) ProtoMessage() {}

func (x *IndexEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gocica_v1_index_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexEntry.ProtoReflect.Descriptor instead.
func (*IndexEntry) Descriptor() ([]byte, []int) {
	return file_gocica_v1_index_entry_proto_rawDescGZIP(), []int{0}
}

func (x *IndexEntry) GetDiskPath() string {
	if x != nil {
		return x.DiskPath
	}
	return ""
}

func (x *IndexEntry) GetOutputId() string {
	if x != nil {
		return x.OutputId
	}
	return ""
}

func (x *IndexEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *IndexEntry) GetTimenano() int64 {
	if x != nil {
		return x.Timenano
	}
	return 0
}

var File_gocica_v1_index_entry_proto protoreflect.FileDescriptor

var file_gocica_v1_index_entry_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x6f, 0x63, 0x69, 0x63, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x2d, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67,
	0x6f, 0x63, 0x69, 0x63, 0x61, 0x2e, 0x76, 0x31, 0x22, 0x76, 0x0a, 0x0a, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x6b, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6e, 0x61, 0x6e, 0x6f,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6e, 0x61, 0x6e, 0x6f,
	0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x61, 0x7a, 0x72, 0x65, 0x61, 0x6e, 0x2f, 0x67, 0x6f, 0x63, 0x69, 0x63, 0x61, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x63, 0x69, 0x63, 0x61, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gocica_v1_index_entry_proto_rawDescOnce sync.Once
	file_gocica_v1_index_entry_proto_rawDescData = file_gocica_v1_index_entry_proto_rawDesc
)

func file_gocica_v1_index_entry_proto_rawDescGZIP() []byte {
	file_gocica_v1_index_entry_proto_rawDescOnce.Do(func() {
		file_gocica_v1_index_entry_proto_rawDescData = protoimpl.X.CompressGZIP(file_gocica_v1_index_entry_proto_rawDescData)
	})
	return file_gocica_v1_index_entry_proto_rawDescData
}

var file_gocica_v1_index_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gocica_v1_index_entry_proto_goTypes = []any{
	(*IndexEntry)(nil), // 0: gocica.v1.IndexEntry
}
var file_gocica_v1_index_entry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gocica_v1_index_entry_proto_init() }
func file_gocica_v1_index_entry_proto_init() {
	if File_gocica_v1_index_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gocica_v1_index_entry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gocica_v1_index_entry_proto_goTypes,
		DependencyIndexes: file_gocica_v1_index_entry_proto_depIdxs,
		MessageInfos:      file_gocica_v1_index_entry_proto_msgTypes,
	}.Build()
	File_gocica_v1_index_entry_proto = out.File
	file_gocica_v1_index_entry_proto_rawDesc = nil
	file_gocica_v1_index_entry_proto_goTypes = nil
	file_gocica_v1_index_entry_proto_depIdxs = nil
}
